### ISSUE TITLE
make vacuum claw suck more

### ISSUE THREAD

**Issue by SiriMoel** [Copious-Modding-Industries/copis_things#23]
**Is your feature request related to a problem? Please describe.**
it doesnt suck enough

**Describe the feature you'd like**
make it more vacuum and suck

**Additional context**
make it suck more

**Comment by Ramiels** [comment]
I think it has decent suction force, have you tried shooting it more?

**Comment by SiriMoel** [comment]
i think its decent but what if you could make it suck more with a modifier or smth or better version yk

**Comment by Ramiels** [comment]
have you heard of divide by two

**Comment by Conga0** [comment]
I'm going to make a PR for copis things with the following changes:

Vacuum Claw now sucks dez nuts

**Comment by Conga0** [comment]
On a more serious note though, I feel like it sucks pretty well as is, slap a chainsaw on it and it's overkill, unless you're trying to suck around suns with it I'm not sure what could require more suction power

**Comment by Ramiels** [comment]
for now I'm leaving it unchanged, as said above just shooting more is enough I think
