### ISSUE TITLE
ophyscupusphshuys arts is too hard to pronounce

### ISSUE THREAD

**Issue by SiriMoel** [Copious-Modding-Industries/copis_things#24]
**Describe the bug**
the name of the funny healing spell is too hard to pronounce mr thing

**To Reproduce**
1. go to spell
2. look at name of spell
3. cry

**Expected behavior**
i should be able to read it without haveing a defficiency

**Screenshots**
no thanks i dont want to have to look at it any further

**Additional context**
there is no additional context but please fix it change it to something like "moldos healing spell" or something cool and amazing like that

**Comment by Ramiels** [comment]
https://www.youtube.com/watch?v=OiRePZgZ13c

**Comment by SiriMoel** [comment]
you are a bad man
