### ISSUE TITLE
where is the mould

### ISSUE THREAD

**Issue by SiriMoel** [Copious-Modding-Industries/copis_things#25]
**Describe the bug**
i was promised by the little birdy that there would be mould n noita in my copy thing? where is this ???

**To Reproduce**
1. start game
2. no mould :(
3. cry
4. download mole's things (copi please do the sprites its been a week)

**Expected behavior**
there will be mould in my copy things

**Screenshots**
no thanks no screen shots here just no mould

**Additional context**
mould n noita has many consequences but now it is gone and we need it back copy thing

**Comment by Ramiels** [comment]
mole please stop making off topic issues on my mod

**Comment by SiriMoel** [comment]
if you want me to stop then make my sprites that you said you would and then ill stop thanks copy
