### ISSUE TITLE
The pop-ups and text to download the mod won't stop showing up

### ISSUE THREAD

**Issue by Eika-Akatosh** [Copious-Modding-Industries/copis_things#28]
**Describe the bug**
Whenever I try to attempt to play Noita, my screen is bombarded with pop-ups and rainbow text telling me to download Copi's Things. I do not know how to disable this, I've tried looking all around the mod data but could find nothing. Please help, I just want to play Noita.

**To Reproduce**
Literally just starting a new game

**Screenshots**
![image](https://github.com/Copious-Modding-Industries/copis_things/assets/147224914/7cf1c712-553a-4b91-9ff0-f49c279ab4fc)

**Additional context**

**Comment by ofoxsmith** [comment]
@GrahamBurgers which graham mod has inbuilt copis things advertising

**Comment by GrahamBurgers** [comment]
dummy turn off mod mimic

**Comment by GrahamBurgers** [comment]
or immersive mimics or whatever it's called

**Comment by Ramiels** [comment]
This is not a copi's things issue, this is an intended feature of the mod "Immersive Mimics" as it's literally a mod mimic pretending to be a legitimate mod

**Comment by Eika-Akatosh** [comment]
> This is not a copi's things issue, this is an intended feature of the mod "Immersive Mimics" as it's literally a mod mimic pretending to be a legitimate mod

Thank you so much

**Comment by Eika-Akatosh** [comment]
Am I able to still use the mod but disable the mod mimic?

**Comment by Ramiels** [comment]
yes

**Comment by Eika-Akatosh** [comment]
How do I disable the mod mimic?

**Comment by Ramiels** [comment]
locate immersive mimics in your mods list, and disable it

**Comment by SiriMoel** [comment]
i think im going to use this
