### ISSUE TITLE
copey thin features reuqst

### ISSUE THREAD

**Issue by ofoxsmith** [Copious-Modding-Industries/copis_things#29]
**Is your feature request related to a problem? Please describe.**
okay so copi hi its me youre betfrstifend moldos mina hello noita im here with a great feature reuqirest for you
so basically my feature is please add mould n noita to the copie things

**Describe the feature you'd like**
A clear and concise description of what you want to happen
sok like when there was mould n noita everyone was happy but now i have depressionand i thnik thats because theres no mould n noita in copyies thing??

**Additional context**
please save my pderession copey things thankyou i love you

-moldos

**Comment by ofoxsmith** [comment]
copi they stole my laptop

**Comment by SiriMoel** [comment]
copey this wasnt me 😿

**Comment by SiriMoel** [comment]
open it please it has not been fulfifliedl
